# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.2.0-13-g19dcd4a
_src_path: git@github.com:MeteoSwiss-APN/mch-python-blueprint.git
email: simon.adamov@meteoswiss.ch
full_name: Simon Adamov
github_username: sadamov
module_name: realtime_pollen_calibration
project_doc_url: https://github.io/sadamov/realtime-pollen-calibration
project_github: MeteoSwiss-APN/realtime-pollen-calibration
project_keywords: Realtime Pollen Calibration
project_name: Realtime Pollen Calibration
project_short_description: Simon Adamov's Realtime Pollen Calibration
project_slug: realtime-pollen-calibration
project_ssh_url: MeteoSwiss-APN/realtime-pollen-calibration.git
python_version: '3.10'
version: 0.1.0
year: '2022'
