# Default configuration used by CI/CD.
# You can run locally 'mchbuild build' to create the images,
# 'mchbuild test' to run the tests using the images. The 'deploy' steps
# can be run separately.
default:
  - build:
      - getSemanticVersion:
          - gitCalculateSemanticVersion:
      - imageTester:
          containerBuildImage:
            imageName: ${var.image}-tester
            imageTag: ${var.semanticVersion}
            target: tester
            extraArgs:
              - --build-arg
              - VERSION=${var.semanticVersion}
      - imageRunner:
          containerBuildImage:
            imageName: ${var.image}
            imageTag: ${var.semanticVersion}
            target: runner
            extraArgs:
              - --build-arg
              - VERSION=${var.semanticVersion}
            pullAlways: false
      - docs:
          - script: mkdir -p doc/_build
          - pythonDocs:
              imageName: ${var.image}-tester
              imageTag: ${var.semanticVersion}
              packageManager: ''
              pullAlways: false
  - test:
      - getSemanticVersion:
          - gitCalculateSemanticVersion:
      - unit:
          - script: mkdir -p test_reports
          - pythonContainerTest:
              imageName: ${var.image}-tester
              imageTag: ${var.semanticVersion}
              packageManager: ''
              pullAlways: false
          - pythonCoverage:
              imageName: ${var.image}-tester
              imageTag: ${var.semanticVersion}
              packageManager: ''
              pullAlways: false
      - lint:
          - script: mkdir -p test_reports
          - pythonContainerLint:
              imageName: ${var.image}-tester
              imageTag: ${var.semanticVersion}
              packageManager: ''
              pullAlways: false
          - pythonContainerTypeCheck:
              imageName: ${var.image}-tester
              imageTag: ${var.semanticVersion}
              packageManager: ''
              pullAlways: false
  - verify:
      - imageSecurityScan:
          - securityReport:
              format: [ 'html', 'sbom', 'table', 'print']
              severity: [ 'CRITICAL', 'HIGH' ]
              removeLocalImage: false
              pullAlways: false
              qualityGate:
                threshold: 20
                criticalFactor: 5
                highFactor: 1
      - publishSbom:
          - securityPublishSbom:
  - deploy:
      - addNextTag:
          gitAddNextTag:
      - addTag:
          gitAddTag:
      - docs:
          openshiftPublishDocs:
            docSrc: doc/_build/
            docType: python
      - image:
          containerPublishImage:
            removeLocalImage: false
      - cpDelete:
          openshiftDelete:
      - cp:
          openshiftDeploy:
            restartDeployment: false
  - clean:
      - getSemanticVersion:
          - gitCalculateSemanticVersion:
      - images:
          script: |
            if test -n "${var.semanticVersion}"; then
              podman image rm -f $(podman image ls -q \
                -f "label=ch.meteoswiss.project=${var.project}-${var.semanticVersion}") || :
            fi

# Alternative configuration to install and test the service locally using
# the local Python installation. Besides 'mchbuild local.build' and
# 'mchbuild local.test' it is possible to run the job using
# 'mchbuild local.run'.
local:
  - build:
      - install:
          pythonInstall:
      - docs:
          pythonDocs:
      - format:
          pythonFormat:
            inPlace: true
  - test:
      - unit:
          - script: mkdir -p test_reports
          - pythonContainerTest:
          - pythonCoverage:
      - lint:
          - script: mkdir -p test_reports
          - pythonContainerLint:
          - pythonContainerTypeCheck:
  - run:
      - main:
          - pythonLocalRunTask:
              commands: realtime-pollen-calibration update_phenology --help

# Configuration to install and test the python project
# on top of a conda environment using micromamba to set it up
conda:
  - build:
      - getSemanticVersion:
          - gitCalculateSemanticVersion:
      - install:
          pythonLocalRunTask:
            packageManager: micromamba
            commands: |
              micromamba create -y -n ${var.project}-${var.semanticVersion} --file conda_deps.yml --rc-file .mambarc && 
              micromamba run -n ${var.project}-${var.semanticVersion} poetry install &&
              echo "Activate your environment with 'micromamba activate ${var.project}-${var.semanticVersion}'"
  - test:
      - getSemanticVersion:
          - gitCalculateSemanticVersion:
      - unit:
          pythonLocalRunTask:
            packageManager: micromamba
            commands: |
              micromamba run -n ${var.project}-${var.semanticVersion} bash -c "mchbuild local.test.unit"
      - lint:
          pythonLocalRunTask:
            packageManager: micromamba
            commands: |
              micromamba run -n ${var.project}-${var.semanticVersion} bash -c "mchbuild local.test.lint"
  - run:
      - getSemanticVersion:
          - gitCalculateSemanticVersion:
      - main:
          - pythonLocalRunTask:
              packageManager: micromamba
              commands: |
                micromamba run -n ${var.project}-${var.semanticVersion} bash -c "mchbuild local.run.main"
  - clean:
      - getSemanticVersion:
          - gitCalculateSemanticVersion:
      - deleteCondaEnv:
          pythonLocalRunTask:
            packageManager: micromamba
            commands: |
              micromamba env remove -y -n ${var.project}-${var.semanticVersion}

variables:
  project: realtime-pollen-calibration
  solution: icon
  semanticVersion: 0.0.0  # is overwritten in Jenkins
