channels:
  - conda-forge
  - defaults
  - r
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - alsa-lib
  - attr
  - attrs
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  - ca-certificates
  - cartopy
  - certifi
  - cffi
  - cfgrib
  - click
  - contourpy
  - curl
  - cycler
  - dbus
  - docrep
  - eccodes
  - expat
  - fftw
  - findlibs
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freeglut
  - freetype
  - funcargparse
  - geos
  - gettext
  - glib
  - glib-tools
  - gst-plugins-base
  - gstreamer
  - gstreamer-orc
  - hdf4
  - hdf5
  - icu
  - jack
  - jasper
  - jpeg
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libaec
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang
  - libclang13
  - libcups
  - libcurl
  - libdb
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libflac
  - libgcc-ng
  - libgcrypt
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libglu
  - libgomp
  - libgpg-error
  - libiconv
  - liblapack
  - libllvm15
  - libnetcdf
  - libnghttp2
  - libnsl
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - libsndfile
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libsystemd0
  - libtiff
  - libtool
  - libudev1
  - libuuid
  - libvorbis
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzip
  - libzlib
  - lz4-c
  - matplotlib
  - matplotlib-base
  - mpg123
  - munkres
  - mysql-common
  - mysql-libs
  - ncurses
  - nspr
  - nss
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pcre2
  - pillow
  - pip
  - ply
  - proj
  - psyplot
  - pthread-stubs
  - pulseaudio
  - pycparser
  - pyparsing
  - pyproj
  - pyqt
  - pyqt5-sip
  - pyshp
  - python
  - python-dateutil
  - python-eccodes
  - python_abi
  - pytz
  - pyyaml
  - qt-main
  - readline
  - scipy
  - setuptools
  - shapely
  - sip
  - six
  - sqlite
  - tk
  - toml
  - tornado
  - tzdata
  - wheel
  - xarray
  - xcb-util
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - iconarray
    - patsy
    - psy-maps
    - psy-reg
    - psy-simple
    - statsmodels
    - install -e .
